"""drop event_matching_mode and event_constraints from subscriptions

Revision ID: 7d2fe63af1fd
Revises: b24ba0c4180a
Create Date: 2026-03-19 16:32:19.418436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d2fe63af1fd'
down_revision: Union[str, Sequence[str], None] = 'b24ba0c4180a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'event_matching_mode')
    op.drop_column('subscriptions', 'event_constraints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('event_constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('event_matching_mode', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
