"""Drop event columns from news_items

Revision ID: b24ba0c4180a
Revises: 53a0c695cb2a
Create Date: 2026-03-19 01:02:17.875549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24ba0c4180a'
down_revision: Union[str, Sequence[str], None] = '53a0c695cb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_items', 'event_starts_at')
    op.drop_column('news_items', 'event_title')
    op.drop_column('news_items', 'event_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('event_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('news_items', sa.Column('event_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('news_items', sa.Column('event_starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
